stages:
  - Prepare
  - Check
  - Test with Clang
  - Test with GCC
  - Test with MSVC
  - Build Documentation
  - Publish

variables:
  HASH_TABLES_VERSION: "0.3.0"
  CONAN_USER: "MusicScience37"
  SECURE_LOG_LEVEL: debug
  CPP_STAT_BENCH_CONAN_REGISTRY: "https://gitlab.com/api/v4/projects/32226502/packages/conan"
  CPP_HASH_TABLES_CONAN_REGISTRY: "https://gitlab.com/api/v4/projects/35726343/packages/conan"

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
sast:
  stage: Check
  needs: []
dependency_scanning:
  stage: Check
  needs:
    - prepare lock files
  dependencies:
    - prepare lock files
license_scanning:
  stage: Check
  needs:
    - prepare lock files
  dependencies:
    - prepare lock files

.retry setting:
  retry:
    max: 1
    when: always

sync pipenv:
  extends: .retry setting
  stage: Prepare
  image: musicscience37/clang-ci:clang14
  script:
    - mkdir -p .venv
    - pipenv sync --dev
  cache:
    key:
      prefix: pipenv-linux
      files:
        - Pipfile.lock
    paths:
      - .venv
  artifacts:
    paths:
      - .venv
    expire_in: "1 mos"

prepare lock files:
  extends: .retry setting
  stage: Prepare
  needs: []
  image: musicscience37/clang-ci:clang14
  script:
    - pipenv sync --dev
    - pipenv run conan profile new --detect default
    - pipenv run conan profile update settings.compiler.libcxx=libc++ default
    - pipenv run conan remote add cpp-stat-bench $CPP_STAT_BENCH_CONAN_REGISTRY
    - pipenv run conan install --build missing -o cpp_hash_tables:requirements_for_tests=True -s build_type=Debug .
  cache:
    key:
      prefix: pipenv-linux-prepare
      files:
        - Pipfile.lock
    paths:
      - .venv
  artifacts:
    paths:
      - conan.lock
    expire_in: "1 mos"

line count:
  extends: .retry setting
  stage: Prepare
  dependencies: []
  image: registry.gitlab.com/musicscience37projects/docker/cloc-docker
  script:
    - mkdir -p line_count
    - cloc ./
      --exclude-dir=line_count
      --force-lang=C++,h
      --json --out=line_count/line_count.json
    - cloc ./include
      --force-lang=C++,h
      --json --out=line_count/src_line_count.json
  artifacts:
    paths:
      - line_count
    expire_in: "1 mos"

pre-commit:
  stage: Check
  needs:
    - sync pipenv
  dependencies:
    - sync pipenv
  image: musicscience37/clang-ci:clang14
  script:
    - pipenv run pre-commit run --all-files

static analysis:
  extends: .retry setting
  stage: Check
  needs:
    - sync pipenv
  dependencies:
    - sync pipenv
  image: musicscience37/clang-ci:clang14
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - apt update
    - apt install -y libstdc++-10-dev
    - pip3 install junit2html
    - mkdir build_static_analysis
    - cd build_static_analysis
    - git clone https://github.com/PSPDFKit-labs/clang-tidy-to-junit.git
    - cd ../
  script:
    - cd build_static_analysis
    - pipenv run conan profile new --detect default
    - pipenv run conan profile update settings.compiler.libcxx=libstdc++11 default
    - pipenv run conan remote add cpp-stat-bench $CPP_STAT_BENCH_CONAN_REGISTRY
    - pipenv run conan install --build missing -o cpp_hash_tables:requirements_for_tests=True ..
    - cd ../
    - cmake -S ./ -B build_static_analysis
      -DHASH_TABLES_ENABLE_CLANG_TIDY:BOOL=ON
      -DHASH_TABLES_TESTING:BOOL=ON
      -DHASH_TABLES_ENABLE_BENCH=ON
      -DHASH_TABLES_BUILD_EXAMPLES=ON
      -DHASH_TABLES_ENABLE_CPP_WARNINGS:BOOL=ON
    - cmake --build build_static_analysis
      --target hash_tables_clang_tidy
    - scripts/check_clang_tidy.sh build_static_analysis/clang_tidy
  after_script:
    - cd build_static_analysis/clang_tidy
    - cat $(find $1 -name '*.txt') |
      python3 ../clang-tidy-to-junit/clang-tidy-to-junit.py $(dirname $(pwd)) > clang_tidy_junit.xml
    - python3 -m junit2htmlreport clang_tidy_junit.xml clang_tidy_junit.html
  artifacts:
    paths:
      - build_static_analysis
    reports:
      junit:
        - build_static_analysis/clang_tidy/clang_tidy_junit.xml
    when: always
    expire_in: "3 mos"

.release-test-base:
  extends: .retry setting
  needs:
    - sync pipenv
  dependencies:
    - sync pipenv
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - pipenv run conan profile new --detect default
    - pipenv run conan profile update settings.compiler.libcxx=libstdc++11 default
    - pipenv run conan remote add cpp-stat-bench $CPP_STAT_BENCH_CONAN_REGISTRY
    - pipenv run conan install --build missing -o cpp_hash_tables:requirements_for_tests=True -s build_type=Release ..
    - cd ../
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Release
      -DHASH_TABLES_TESTING:BOOL=ON
      -DHASH_TABLES_ENABLE_BENCH=ON
      -DHASH_TABLES_TEST_BENCHMARKS=ON
      -DHASH_TABLES_BUILD_EXAMPLES=ON
      -DHASH_TABLES_TEST_EXAMPLES=ON
      -DHASH_TABLES_WRITE_JUNIT:BOOL=ON
    - cd $BUILD_DIR
    - cmake --build .
    - ctest -V
  artifacts:
    paths:
      - $BUILD_DIR
      - "*.png"
      - "*.html"
    reports:
      junit:
        - $BUILD_DIR/junit/*.xml
    when: always
    expire_in: "1 mos"

.debug-test-base:
  extends: .release-test-base
  before_script:
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - pipenv run conan profile new --detect default
    - pipenv run conan profile update settings.compiler.libcxx=libstdc++11 default
    - pipenv run conan remote add cpp-stat-bench $CPP_STAT_BENCH_CONAN_REGISTRY
    - pipenv run conan install --build missing -o cpp_hash_tables:requirements_for_tests=True -s build_type=Debug ..
    - cd ../
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Debug
      -DHASH_TABLES_TESTING:BOOL=ON
      -DHASH_TABLES_BUILD_EXAMPLES=ON
      -DHASH_TABLES_TEST_EXAMPLES=ON
      -DHASH_TABLES_WRITE_JUNIT:BOOL=ON
    - cd $BUILD_DIR
    - cmake --build .
    - ctest -V

.clang-release-test-base:
  extends: .release-test-base
  before_script:
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - pipenv run conan profile new --detect default
    - pipenv run conan profile update settings.compiler.libcxx=libc++ default
    - pipenv run conan remote add cpp-stat-bench $CPP_STAT_BENCH_CONAN_REGISTRY
    - pipenv run conan install --build missing -o cpp_hash_tables:requirements_for_tests=True -s build_type=Release ..
    - cd ../

.clang-debug-test-base:
  extends: .release-test-base
  before_script:
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - pipenv run conan profile new --detect default
    - pipenv run conan profile update settings.compiler.libcxx=libc++ default
    - pipenv run conan remote add cpp-stat-bench $CPP_STAT_BENCH_CONAN_REGISTRY
    - pipenv run conan install --build missing -o cpp_hash_tables:requirements_for_tests=True -s build_type=Debug ..
    - cd ../

clang coverage:
  extends: .clang-debug-test-base
  stage: Test with Clang
  image: musicscience37/clang-ci:clang14
  variables:
    BUILD_DIR: build_clang_coverage
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Debug
      -DHASH_TABLES_TESTING:BOOL=ON
      -DHASH_TABLES_WRITE_JUNIT:BOOL=ON
      -DHASH_TABLES_ENABLE_INTEG_TESTS:BOOL=OFF
      "-DCMAKE_CXX_FLAGS=-fprofile-instr-generate -fcoverage-mapping"
      "-DCMAKE_MODULE_LINKER_FLAGS=-fprofile-instr-generate -fcoverage-mapping"
    - cd $BUILD_DIR
    - mkdir coverage
    - export LLVM_PROFILE_FILE=$(pwd)/coverage/coverage_%p.profraw
    - cmake --build .
    - ctest -V
    - cd ../
    - scripts/collect_llvm_coverage.sh build_clang_coverage

gcc coverage:
  extends: .debug-test-base
  stage: Test with GCC
  image: musicscience37/gcc-ci:gcc10
  variables:
    BUILD_DIR: build_gcc_coverage
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Debug
      -DHASH_TABLES_TESTING:BOOL=ON
      -DHASH_TABLES_WRITE_JUNIT:BOOL=ON
      -DHASH_TABLES_ENABLE_INTEG_TESTS:BOOL=OFF
      "-DCMAKE_CXX_FLAGS=--coverage"
      "-DCMAKE_MODULE_LINKER_FLAGS=--coverage"
    - cd $BUILD_DIR
    - cmake --build .
    - ctest -V
    - cd ../
    - scripts/collect_gcc_coverage.sh build_gcc_coverage
  coverage: '/Total:\|\s*(\d+\.?\d+?)%/'

gcc-10-debug:
  extends: .debug-test-base
  stage: Test with GCC
  image: musicscience37/gcc-ci:gcc10
  variables:
    BUILD_DIR: build_gcc10_debug

gcc-10-release:
  extends: .release-test-base
  stage: Test with GCC
  image: musicscience37/gcc-ci:gcc10
  variables:
    BUILD_DIR: build_gcc10_release

gcc-12-debug:
  extends: .debug-test-base
  stage: Test with GCC
  image: musicscience37/gcc-ci:gcc12
  variables:
    BUILD_DIR: build_gcc12_debug

clang-14-release:
  extends: .clang-release-test-base
  stage: Test with Clang
  image: musicscience37/clang-ci:clang14
  variables:
    BUILD_DIR: build_clang14_release

clang-15-debug:
  extends: .clang-debug-test-base
  stage: Test with Clang
  image: musicscience37/clang-ci:clang15
  variables:
    BUILD_DIR: build_clang15_debug

clang-14-asan-ubsan:
  extends: .clang-debug-test-base
  stage: Test with Clang
  image: musicscience37/clang-ci:clang14
  variables:
    BUILD_DIR: build_clang_asan_ubsan
    ASAN_OPTIONS: alloc_dealloc_mismatch=0
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Debug
      -DHASH_TABLES_TESTING:BOOL=ON
      -DHASH_TABLES_WRITE_JUNIT:BOOL=ON
      -DHASH_TABLES_ENABLE_AUSAN:BOOL=ON
    - cd $BUILD_DIR
    - cmake --build .
    - ctest -V

msvc-release:
  extends: .release-test-base
  tags:
    - shared-windows
    - windows
    - windows-1809
  stage: Test with MSVC
  needs: []
  dependencies: []
  variables:
    BUILD_DIR: build_msvc_release
    CONAN_USER_HOME: C:\Users\gitlab_runner
    CONAN_USE_ALWAYS_SHORT_PATHS: 1
  before_script:
    - (mv ${CI_PROJECT_DIR}/.conan C:\Users\gitlab_runner -Force)
    - Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
    - choco install cmake -y --installargs 'ADD_CMAKE_TO_PATH=System'
    - choco install python --version=3.10.8 -y
    - RefreshEnv
    - pip install pipenv
    - pipenv sync
    - pipenv clean
  script:
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - pipenv run conan profile new --detect default
    - pipenv run conan remote add cpp-stat-bench $CPP_STAT_BENCH_CONAN_REGISTRY
    - pipenv run conan install --build missing -o cpp_hash_tables:requirements_for_tests=True -s build_type=Release ..
    - cd ../
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Release
      -DHASH_TABLES_TESTING:BOOL=ON
      -DHASH_TABLES_ENABLE_BENCH=ON
      -DHASH_TABLES_TEST_BENCHMARKS=ON
      -DHASH_TABLES_BUILD_EXAMPLES=ON
      -DHASH_TABLES_TEST_EXAMPLES=ON
      -DHASH_TABLES_WRITE_JUNIT:BOOL=ON
    - cd $BUILD_DIR
    - cmake --build . --config Release --parallel
    - ctest -V --build-config Release
  after_script:
    - (mv C:\Users\gitlab_runner\.conan ${CI_PROJECT_DIR} -Force)
  allow_failure: true

clang-14-conan:
  extends: .retry setting
  stage: Test with Clang
  needs:
    - sync pipenv
  dependencies:
    - sync pipenv
  image: musicscience37/clang-ci:clang14
  variables:
    CONAN_CHANNEL: "testing"
  script:
    - pipenv run conan profile new --detect default
    - pipenv run conan profile update settings.compiler.libcxx=libc++ default
    - pipenv run conan remote add cpp-stat-bench $CPP_STAT_BENCH_CONAN_REGISTRY
    - pipenv run conan create --build missing --test-folder tests/conan_package -s build_type=Debug . ${CONAN_USER}/${CONAN_CHANNEL}
    - pipenv run conan create --build missing --test-folder tests/conan_package -s build_type=Release . ${CONAN_USER}/${CONAN_CHANNEL}

clang-14-conan-release:
  extends: .retry setting
  stage: Publish
  needs:
    - sync pipenv
  dependencies:
    - sync pipenv
  image: musicscience37/clang-ci:clang14
  variables:
    CONAN_CHANNEL: "stable"
  script:
    - pipenv run conan profile new --detect default
    - pipenv run conan profile update settings.compiler.libcxx=libc++ default
    - pipenv run conan remote add cpp-stat-bench $CPP_STAT_BENCH_CONAN_REGISTRY
    - pipenv run conan remote add cpp-hash-tables $CPP_HASH_TABLES_CONAN_REGISTRY
    - pipenv run conan create --build missing --test-folder tests/conan_package -s build_type=Debug . ${CONAN_USER}/${CONAN_CHANNEL}
    - pipenv run conan create --build missing --test-folder tests/conan_package -s build_type=Release . ${CONAN_USER}/${CONAN_CHANNEL}
    - CONAN_LOGIN_USERNAME=ci_user CONAN_PASSWORD=${CI_JOB_TOKEN} pipenv run conan upload -r cpp-hash-tables cpp_hash_tables/${HASH_TABLES_VERSION}@${CONAN_USER}/${CONAN_CHANNEL} --all
  only:
    - tags

doc:
  extends: .retry setting
  stage: Build Documentation
  needs:
    - sync pipenv
  dependencies:
    - sync pipenv
  image: musicscience37/sphinx-doxygen:clang14
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - mkdir build_doc
    - cd build_doc
    - pipenv run conan profile new --detect default
    - pipenv run conan profile update settings.compiler.libcxx=libc++ default
    - pipenv run conan remote add cpp-stat-bench $CPP_STAT_BENCH_CONAN_REGISTRY
    - pipenv run conan install --build missing -o cpp_hash_tables:requirements_for_tests=True ..
    - cd ../
    - cmake -S ./ -B build_doc
      -DHASH_TABLES_BUILD_DOC:BOOL=ON
    - cmake --build build_doc --target hash_tables_doc
  artifacts:
    paths:
      - build_doc
    when: always
    expire_in: "3 mos"

pages:
  extends: .retry setting
  stage: Publish
  only:
    - develop
  needs:
    - doc
  dependencies:
    - doc
  script:
    - rm -rf public
    - mv build_doc/doc/html public
  artifacts:
    paths:
      - public
