stages:
  - prepare
  - test
  - deploy
  - release

variables:
  HASH_TABLES_VERSION: "0.4.1"
  CONAN_USER: "MusicScience37"
  SECURE_LOG_LEVEL: debug
  CPP_STAT_BENCH_CONAN_REGISTRY: "https://gitlab.com/api/v4/projects/32226502/packages/conan"
  CPP_HASH_TABLES_CONAN_REGISTRY: "https://gitlab.com/api/v4/projects/35726343/packages/conan"

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
sast:
  needs: []
dependency_scanning:
  needs:
    - prepare lock files
  dependencies:
    - prepare lock files
license_scanning:
  needs:
    - prepare lock files
  dependencies:
    - prepare lock files

sync poetry:
  stage: prepare
  image: musicscience37/clang-ci:clang14
  script:
    - mkdir -p .venv
    - poetry config virtualenvs.in-project true
    - poetry env use 3.10
    - poetry install
  cache:
    key:
      prefix: poetry-linux
      files:
        - Poetry.lock
    paths:
      - .venv
  artifacts:
    paths:
      - .venv
    expire_in: "1 mos"

prepare lock files:
  stage: prepare
  needs: []
  image: musicscience37/clang-ci:clang14
  script:
    - poetry config virtualenvs.in-project true
    - poetry env use 3.10
    - poetry install
    - poetry run conan profile new --detect default
    - poetry run conan profile update settings.compiler.libcxx=libc++ default
    - poetry run conan remote add cpp-stat-bench $CPP_STAT_BENCH_CONAN_REGISTRY
    - poetry run conan install --build missing -o cpp_hash_tables:requirements_for_tests=True -s build_type=Debug .
  cache:
    key:
      prefix: poetry-linux-prepare
      files:
        - Poetry.lock
    paths:
      - .venv
  artifacts:
    paths:
      - conan.lock
    expire_in: "1 mos"

line count:
  stage: prepare
  dependencies: []
  image: registry.gitlab.com/musicscience37projects/docker/cloc-docker
  script:
    - mkdir -p line_count
    - cloc ./
      --exclude-dir=line_count
      --force-lang=C++,h
      --json --out=line_count/line_count.json
    - cloc ./include
      --force-lang=C++,h
      --json --out=line_count/src_line_count.json
  artifacts:
    paths:
      - line_count
    expire_in: "1 mos"

pre-commit:
  stage: test
  needs:
    - sync poetry
  dependencies:
    - sync poetry
  image: musicscience37/clang-ci:clang14
  script:
    - poetry run pre-commit run --all-files

test release:
  needs:
    - sync poetry
  dependencies:
    - sync poetry
  parallel:
    matrix:
      - COMPILER_TYPE: ["gcc10", "gcc12"]
        IMAGE_PATH: "musicscience37/gcc-ci"
        CONAN_LIBCXX: libstdc++11
        CXX_STANDARD: 14
      - COMPILER_TYPE: ["clang14", "clang15"]
        IMAGE_PATH: "musicscience37/clang-ci"
        CONAN_LIBCXX: libc++
        CXX_STANDARD: 14
      - COMPILER_TYPE: ["clang14"]
        IMAGE_PATH: "musicscience37/clang-ci"
        CONAN_LIBCXX: libc++
        CXX_STANDARD: 20
  image: ${IMAGE_PATH}:${COMPILER_TYPE}
  variables:
    BUILD_TYPE: Release
    BUILD_DIR: build_${COMPILER_TYPE}_release
  before_script:
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - poetry run conan profile new --detect default
    - poetry run conan profile update settings.compiler.libcxx=$CONAN_LIBCXX default
    - poetry run conan remote add cpp-stat-bench $CPP_STAT_BENCH_CONAN_REGISTRY
    - poetry run conan install --build missing -o cpp_hash_tables:requirements_for_tests=True -s build_type=$BUILD_TYPE ..
    - cd ../
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      -DHASH_TABLES_TESTING:BOOL=ON
      -DHASH_TABLES_ENABLE_BENCH=ON
      -DHASH_TABLES_TEST_BENCHMARKS=ON
      -DHASH_TABLES_BUILD_EXAMPLES=ON
      -DHASH_TABLES_TEST_EXAMPLES=ON
      -DHASH_TABLES_WRITE_JUNIT:BOOL=ON
      -DCMAKE_CXX_STANDARD=$CXX_STANDARD
    - cd $BUILD_DIR
    - cmake --build .
    - ctest -V
  artifacts:
    paths:
      - $BUILD_DIR/bench
      - $BUILD_DIR/junit
      - $BUILD_DIR/temp_test
      - $BUILD_DIR/coverage
      - "*.png"
      - "*.html"
    reports:
      junit:
        - $BUILD_DIR/junit/*.xml
    when: always
    expire_in: "1 mos"

test debug:
  extends: test release
  parallel:
    matrix:
      - COMPILER_TYPE: ["gcc10"]
        IMAGE_PATH: "musicscience37/gcc-ci"
        CONAN_LIBCXX: libstdc++11
        CXX_STANDARD: 14
      - COMPILER_TYPE: ["clang14"]
        IMAGE_PATH: "musicscience37/clang-ci"
        CONAN_LIBCXX: libc++
        CXX_STANDARD: 14
  variables:
    BUILD_TYPE: Debug
    BUILD_DIR: build_${COMPILER_TYPE}_debug
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      -DHASH_TABLES_TESTING:BOOL=ON
      -DHASH_TABLES_BUILD_EXAMPLES=ON
      -DHASH_TABLES_TEST_EXAMPLES=ON
      -DHASH_TABLES_WRITE_JUNIT:BOOL=ON
      -DCMAKE_CXX_STANDARD=$CXX_STANDARD
    - cd $BUILD_DIR
    - cmake --build .
    - ctest -V

clang coverage:
  extends: test debug
  parallel:
    matrix:
      - COMPILER_TYPE: "clang14"
        IMAGE_PATH: "musicscience37/clang-ci"
        CONAN_LIBCXX: libc++
        CXX_STANDARD: 14
  variables:
    BUILD_DIR: build_clang_coverage
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Debug
      -DHASH_TABLES_TESTING:BOOL=ON
      -DHASH_TABLES_WRITE_JUNIT:BOOL=ON
      -DHASH_TABLES_ENABLE_INTEG_TESTS:BOOL=OFF
      "-DCMAKE_CXX_FLAGS=-fprofile-instr-generate -fcoverage-mapping"
      "-DCMAKE_MODULE_LINKER_FLAGS=-fprofile-instr-generate -fcoverage-mapping"
    - cd $BUILD_DIR
    - mkdir coverage
    - export LLVM_PROFILE_FILE=$(pwd)/coverage/coverage_%p.profraw
    - cmake --build .
    - ctest -V
    - cd ../
    - scripts/collect_llvm_coverage.sh build_clang_coverage
  coverage: '/[^\s]+%\s+\d+\s+\d+\s+\s[^\s]+%/'

clang-14-asan-ubsan:
  extends: test debug
  parallel:
    matrix:
      - COMPILER_TYPE: "clang14"
        IMAGE_PATH: "musicscience37/clang-ci"
        CONAN_LIBCXX: libc++
        CXX_STANDARD: 14
  variables:
    BUILD_DIR: build_clang_asan_ubsan
    ASAN_OPTIONS: alloc_dealloc_mismatch=0
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Debug
      -DHASH_TABLES_TESTING:BOOL=ON
      -DHASH_TABLES_WRITE_JUNIT:BOOL=ON
      -DHASH_TABLES_ENABLE_AUSAN:BOOL=ON
    - cd $BUILD_DIR
    - cmake --build .
    - ctest -V

clang-14-conan:
  stage: test
  needs:
    - sync poetry
  dependencies:
    - sync poetry
  image: musicscience37/clang-ci:clang14
  variables:
    CONAN_CHANNEL: "testing"
  script:
    - poetry run conan profile new --detect default
    - poetry run conan profile update settings.compiler.libcxx=libc++ default
    - poetry run conan remote add cpp-stat-bench $CPP_STAT_BENCH_CONAN_REGISTRY
    - poetry run conan create --build missing --test-folder tests/conan_package -s build_type=Debug . ${CONAN_USER}/${CONAN_CHANNEL}
    - poetry run conan create --build missing --test-folder tests/conan_package -s build_type=Release . ${CONAN_USER}/${CONAN_CHANNEL}

clang-14-conan-release:
  stage: deploy
  needs:
    - sync poetry
  dependencies:
    - sync poetry
  image: musicscience37/clang-ci:clang14
  variables:
    CONAN_CHANNEL: "stable"
  script:
    - poetry run conan profile new --detect default
    - poetry run conan profile update settings.compiler.libcxx=libc++ default
    - poetry run conan remote add cpp-stat-bench $CPP_STAT_BENCH_CONAN_REGISTRY
    - poetry run conan remote add cpp-hash-tables $CPP_HASH_TABLES_CONAN_REGISTRY
    - poetry run conan create --build missing --test-folder tests/conan_package -s build_type=Debug . ${CONAN_USER}/${CONAN_CHANNEL}
    - poetry run conan create --build missing --test-folder tests/conan_package -s build_type=Release . ${CONAN_USER}/${CONAN_CHANNEL}
    - CONAN_LOGIN_USERNAME=ci_user CONAN_PASSWORD=${CI_JOB_TOKEN} poetry run conan upload -r cpp-hash-tables cpp_hash_tables/${HASH_TABLES_VERSION}@${CONAN_USER}/${CONAN_CHANNEL} --all
  only:
    - tags

msvc-release:
  tags:
    - shared-windows
    - windows
    - windows-1809
  stage: test
  needs: []
  dependencies: []
  variables:
    BUILD_DIR: build_msvc_release
    CONAN_USER_HOME: C:\Users\gitlab_runner
    # Workaround in https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=conan_use_always_short_paths#short-paths
    CONAN_USE_ALWAYS_SHORT_PATHS: 1
    # workaround in https://github.com/python-poetry/poetry/issues/1917#issuecomment-1235998997
    PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
  before_script:
    - (mv ${CI_PROJECT_DIR}/.conan C:\Users\gitlab_runner -Force)
    - Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
    - choco install cmake -y --installargs 'ADD_CMAKE_TO_PATH=System'
    - choco install python --version=3.10.8 -y
    - RefreshEnv
    - pip install poetry
    - poetry install
  script:
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - poetry run conan profile new --detect default
    - poetry run conan remote add cpp-stat-bench $CPP_STAT_BENCH_CONAN_REGISTRY
    - poetry run conan install --build missing -o cpp_hash_tables:requirements_for_tests=True -s build_type=Release ..
    - cd ../
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Release
      -DHASH_TABLES_TESTING:BOOL=ON
      -DHASH_TABLES_ENABLE_BENCH=ON
      -DHASH_TABLES_BUILD_EXAMPLES=ON
      -DHASH_TABLES_TEST_EXAMPLES=ON
      -DHASH_TABLES_WRITE_JUNIT:BOOL=ON
    - cd $BUILD_DIR
    - cmake --build . --config Release --parallel
    - ctest -V --build-config Release
  after_script:
    - (mv C:\Users\gitlab_runner\.conan ${CI_PROJECT_DIR} -Force)
  artifacts:
    paths:
      - $BUILD_DIR/bench
      - $BUILD_DIR/junit
      - $BUILD_DIR/temp_test
      - $BUILD_DIR/coverage
      - "*.png"
      - "*.html"
    reports:
      junit:
        - $BUILD_DIR/junit/*.xml
    when: always
    expire_in: "1 mos"

static analysis:
  extends: test release
  parallel:
    matrix:
      - COMPILER_TYPE: "clang14"
        IMAGE_PATH: "musicscience37/clang-ci"
        CONAN_LIBCXX: libc++
        CXX_STANDARD: 14
  variables:
    BUILD_TYPE: Debug
    BUILD_DIR: build_static_analysis
  before_script:
    - apt update
    - apt install -y libstdc++-10-dev
    - pip3 install junit2html
    - mkdir build_static_analysis
    - cd build_static_analysis
    - git clone https://github.com/PSPDFKit-labs/clang-tidy-to-junit.git
    - cd ../
  script:
    - cd build_static_analysis
    - poetry run conan profile new --detect default
    - poetry run conan profile update settings.compiler.libcxx=libstdc++11 default
    - poetry run conan remote add cpp-stat-bench $CPP_STAT_BENCH_CONAN_REGISTRY
    - poetry run conan install --build missing -o cpp_hash_tables:requirements_for_tests=True ..
    - cd ../
    - cmake -S ./ -B build_static_analysis
      -DHASH_TABLES_ENABLE_CLANG_TIDY:BOOL=ON
      -DHASH_TABLES_TESTING:BOOL=ON
      -DHASH_TABLES_ENABLE_BENCH=ON
      -DHASH_TABLES_BUILD_EXAMPLES=ON
      -DHASH_TABLES_ENABLE_CPP_WARNINGS:BOOL=ON
    - cmake --build build_static_analysis
      --target hash_tables_clang_tidy
    - scripts/check_clang_tidy.sh build_static_analysis/clang_tidy
  after_script:
    - cd build_static_analysis/clang_tidy
    - cat $(find $1 -name '*.txt') |
      python3 ../clang-tidy-to-junit/clang-tidy-to-junit.py $(dirname $(pwd)) > clang_tidy_junit.xml
    - python3 -m junit2htmlreport clang_tidy_junit.xml clang_tidy_junit.html
  artifacts:
    paths:
      - build_static_analysis/bench
      - build_static_analysis/junit
      - build_static_analysis/temp_test
    reports:
      junit:
        - build_static_analysis/clang_tidy/clang_tidy_junit.xml
    when: always
    expire_in: "3 mos"

doc:
  stage: test
  needs:
    - sync poetry
  dependencies:
    - sync poetry
  image: musicscience37/sphinx-doxygen:clang14
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - mkdir build_doc
    - cd build_doc
    - poetry run conan profile new --detect default
    - poetry run conan profile update settings.compiler.libcxx=libc++ default
    - poetry run conan remote add cpp-stat-bench $CPP_STAT_BENCH_CONAN_REGISTRY
    - poetry run conan install --build missing -o cpp_hash_tables:requirements_for_tests=True ..
    - cd ../
    - cmake -S ./ -B build_doc
      -DHASH_TABLES_BUILD_DOC:BOOL=ON
    - cmake --build build_doc --target hash_tables_doc
  artifacts:
    paths:
      - build_doc/doc
    when: always
    expire_in: "3 mos"

pages:
  stage: deploy
  only:
    - develop
  needs:
    - doc
  dependencies:
    - doc
  script:
    - rm -rf public
    - mv build_doc/doc/html public
  artifacts:
    paths:
      - public

release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  rules:
    - if: $CI_COMMIT_TAG =~ /^v/
  script:
    - echo "This is a release job."
  release:
    tag_name: $CI_COMMIT_TAG
    name: "$CI_COMMIT_TAG"
    description: "./doc/sphinx/src/change_log/${CI_COMMIT_TAG}.md"
