[tool.poetry]
name = "cpp-hash-tables"
version = "0.0.0"
description = ""
authors = []
readme = "README.md"
packages = [{ include = "scripts" }]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"

[tool.poetry.group.dev.dependencies]
black = "^24.2.0"
breathe = "^4.35.0"
cmakelang = "^0.6.13"
doc8 = "^1.1.1"
myst-parser = "^2.0.0"
pre-commit = "^3.6.1"
pylint = "^3.0.3"
sphinx = "^7.2.6"
sphinx-orange-book-theme = "^0.6.0"
sphinx-autobuild = "^2024.2.4"
sphinxcontrib-plantuml = "^0.27"
mpmath = "^1.3.0"
clang-tidy-checker = "^0.4.0"
lcov-cobertura = "^2.0.2"
click = "^8.1.7"
tqdm = "^4.66.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
