[tool.poetry]
name = "cpp-hash-tables"
version = "0.0.0"
description = ""
authors = []
readme = "README.md"
packages = [{ include = "scripts" }]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"

[tool.poetry.group.dev.dependencies]
black = "^23.9.1"
breathe = "^4.35.0"
cmakelang = "^0.6.13"
doc8 = "^0.11.2"
myst-parser = "^2.0.0"
pre-commit = "^3.4.0"
pylint = "^2.17.5"
sphinx = "^7.2.5"
sphinx-autobuild = "^2021.3.14"
sphinx-rtd-theme = "^1.3.0"
sphinxcontrib-plantuml = "^0.26"
mpmath = "^1.3.0"
clang-tidy-checker = "^0.3.0"
lcov-cobertura = "^2.0.2"
click = "^8.1.7"
tqdm = "^4.66.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
