[tool.poetry]
name = "cpp-hash-tables"
version = "0.0.0"
description = ""
authors = []
readme = "README.md"
packages = [{ include = "scripts" }]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
breathe = "^4.35.0"
cmakelang = "^0.6.13"
doc8 = "^0.11.2"
myst-parser = "^1.0.0"
pre-commit = "^3.2.2"
pylint = "^2.17.2"
sphinx = "^6.1.3"
sphinx-autobuild = "^2021.3.14"
sphinx-rtd-theme = "^1.2.0"
sphinxcontrib-plantuml = "^0.25"
mpmath = "^1.3.0"
clang-tidy-checker = "^0.2.0"
lcov-cobertura = "^2.0.2"
click = "^8.1.3"
tqdm = "^4.65.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
